/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usjt.atividade.views.authentication.SignUp;

import java.awt.*;

/**
 *
 * @author 312221384
 */
public class SignUpPanel extends javax.swing.JPanel {

    /**
     * Creates new form singUpPanel
     */
    public SignUpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTextField = new usjt.atividade.views.authentication.utils.CustomTextField();
        userTextField.setPlaceholderColor(Color.GRAY);
        userTextField.setTextColor(Color.WHITE);
        userTextField.setBorderColor(Color.CYAN);
        userTextField.setPlaceholder("Digite seu usuário...");
        emailLabel = new javax.swing.JLabel();
        emailTextField = new usjt.atividade.views.authentication.utils.CustomTextField();
        emailTextField.setPlaceholder("Digite seu e-mail...");
        emailTextField.setPlaceholderColor(Color.GRAY);
        emailTextField.setTextColor(Color.WHITE);
        emailTextField.setBorderColor(Color.CYAN);
        passwordLabel = new javax.swing.JLabel();
        passwordField = new usjt.atividade.views.authentication.utils.CustomPasswordField();
        passwordField.setPlaceholder("Digite sua senha...");
        passwordField.setPlaceholderColor(Color.GRAY);
        passwordField.setTextColor(Color.WHITE);
        passwordField.setBorderColor(Color.CYAN);
        repeatPasswordLabel = new javax.swing.JLabel();
        repeatPasswordField = new usjt.atividade.views.authentication.utils.CustomPasswordField();
        repeatPasswordField.setPlaceholder("Repita sua senha...");
        repeatPasswordField.setPlaceholderColor(Color.GRAY);
        repeatPasswordField.setTextColor(Color.WHITE);
        repeatPasswordField.setBorderColor(Color.CYAN);
        btnCadastrar = new usjt.atividade.views.authentication.utils.RoundedButton();

        setBackground(new java.awt.Color(0, 33, 66));
        setPreferredSize(new java.awt.Dimension(500, 700));
        
        loginLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginLabel.setForeground(Color.WHITE);
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Cadastre-se");

        userLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Usuário:");
        userLabel.setForeground(Color.WHITE);

        userTextField.setToolTipText("");

        emailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email:");
        emailLabel.setForeground(Color.WHITE);

        emailTextField.setToolTipText("");

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Senha:");
        passwordLabel.setForeground(Color.WHITE);

        repeatPasswordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        repeatPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        repeatPasswordLabel.setText("Repetir senha:");
        repeatPasswordLabel.setForeground(Color.WHITE);

        btnCadastrar.setBackground(new java.awt.Color(0, 140, 160));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setBorderColor(new java.awt.Color(0, 140, 160));
        btnCadastrar.setColorPressed(new java.awt.Color(0, 150, 160));
        btnCadastrar.setColorRollover(new java.awt.Color(0, 160, 170));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatPasswordLabel)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(repeatPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usjt.atividade.views.authentication.utils.RoundedButton btnCadastrar;
    private javax.swing.JLabel emailLabel;
    private usjt.atividade.views.authentication.utils.CustomTextField emailTextField;
    private javax.swing.JLabel loginLabel;
    private usjt.atividade.views.authentication.utils.CustomPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private usjt.atividade.views.authentication.utils.CustomPasswordField repeatPasswordField;
    private javax.swing.JLabel repeatPasswordLabel;
    private javax.swing.JLabel userLabel;
    private usjt.atividade.views.authentication.utils.CustomTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
